<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="sebin" failures="1" tests="4" name="Login-As College" time="22.377" errors="0" timestamp="2024-08-12T10:16:11 IST">
  <testcase classname="com.ospyn.ktu.test.Login" name="ktu_Page_Loaded" time="1.004"/>
  <testcase classname="com.ospyn.ktu.test.Login" name="login_With_Excel" time="0.002"/>
  <testcase classname="com.ospyn.ktu.test.Login" name="click_Login_Button" time="1.15"/>
  <testcase classname="com.ospyn.ktu.test.Login" name="validate_Login_Success" time="20.101">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Success&amp;gt; but was:&amp;lt;&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Success> but was:<>
at com.ospyn.ktu.test.Login.validate_Login_Success(Login.java:136)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_Login_Success -->
  <testcase classname="com.ospyn.ktu.test.Login" name="click_logOut" time="0.0">
    <ignored/>
  </testcase> <!-- click_logOut -->
  <testcase classname="com.ospyn.ktu.test.Login" name="loginUser" time="0.0">
    <ignored/>
  </testcase> <!-- loginUser -->
  <testcase classname="com.ospyn.ktu.test.Login" name="next_College" time="0.0">
    <ignored/>
  </testcase> <!-- next_College -->
</testsuite> <!-- Login-As College -->
